In [36]:
# Importing necessary libraries

import pandas as pd
import duckdb

In [37]:
# Creating connect

con = duckdb.connect("../01_docs/01_data/project.duckdb")

In [38]:
# Testing connection

con.execute(
    """
    SELECT *
    FROM read_parquet('../01_docs/01_data/01_raw/fhvhv_tripdata_2024-07.parquet')
    LIMIT 10
    """
).df()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag
0,HV0003,B03404,B03404,2024-07-01 00:13:16,2024-07-01 00:18:28,2024-07-01 00:19:43,2024-07-01 00:40:35,138,141,8.840,...,4.70,2.75,2.5,9.28,24.19,N,N,N,N,N
1,HV0003,B03404,B03404,2024-07-01 00:16:44,2024-07-01 00:18:58,2024-07-01 00:21:00,2024-07-01 00:41:24,61,80,3.960,...,2.22,0.00,0.0,0.00,19.37,N,N,N,N,N
2,HV0003,B03404,B03404,2024-07-01 00:38:38,2024-07-01 00:45:10,2024-07-01 00:45:10,2024-07-01 01:01:05,36,260,5.610,...,1.84,0.00,0.0,0.00,12.08,Y,Y,N,N,N
3,HV0003,B03404,B03404,2024-07-01 00:38:26,2024-07-01 00:48:38,2024-07-01 00:49:01,2024-07-01 01:15:02,80,42,11.240,...,4.05,0.00,0.0,0.00,25.64,Y,Y,N,N,N
4,HV0003,B03404,B03404,2024-07-01 00:34:57,2024-07-01 00:40:58,2024-07-01 00:41:36,2024-07-01 00:49:48,152,41,1.600,...,1.03,0.00,0.0,5.00,7.11,N,N,N,N,N
5,HV0005,B03406,NaN,2024-07-01 00:36:16,NaT,2024-07-01 00:44:05,2024-07-01 00:54:37,138,92,3.343,...,1.93,0.00,2.5,0.00,11.45,N,N,N,N,N
6,HV0003,B03404,B03404,2024-07-01 00:05:41,2024-07-01 00:09:27,2024-07-01 00:09:49,2024-07-01 00:35:52,164,17,5.520,...,3.27,2.75,0.0,0.00,25.95,N,N,N,N,N
7,HV0003,B03404,B03404,2024-07-01 00:36:11,2024-07-01 00:40:27,2024-07-01 00:41:13,2024-07-01 00:49:39,37,225,1.680,...,1.19,0.00,0.0,0.00,8.19,N,N,N,N,N
8,HV0003,B03404,B03404,2024-07-01 00:48:32,2024-07-01 00:50:15,2024-07-01 00:51:13,2024-07-01 01:21:50,225,79,6.860,...,1.55,0.75,0.0,0.00,16.04,Y,Y,N,N,N
9,HV0003,B03404,B03404,2024-07-01 00:47:59,2024-07-01 00:52:47,2024-07-01 00:53:03,2024-07-01 01:01:39,17,49,1.370,...,0.43,0.00,0.0,0.00,2.95,Y,Y,N,N,N

In [39]:
# Creating a view

def create_view(con, category):
    con.execute(
        f"""
        CREATE OR REPLACE VIEW {category} AS
        SELECT *
        FROM read_parquet('../01_docs/01_data/01_raw/{category}_tripdata_2024-**.parquet')
        """
        )


create_view(con, 'fhvhv')

create_view(con, 'fhv')

create_view(con, 'green')

create_view(con, 'yellow')

In [40]:
# Checking features of the created views

con.execute("DESCRIBE fhvhv").df()

             column_name column_type null   key default extra
0      hvfhs_license_num     VARCHAR  YES  None    None  None
1   dispatching_base_num     VARCHAR  YES  None    None  None
2   originating_base_num     VARCHAR  YES  None    None  None
3       request_datetime   TIMESTAMP  YES  None    None  None
4      on_scene_datetime   TIMESTAMP  YES  None    None  None
5        pickup_datetime   TIMESTAMP  YES  None    None  None
6       dropoff_datetime   TIMESTAMP  YES  None    None  None
7           PULocationID     INTEGER  YES  None    None  None
8           DOLocationID     INTEGER  YES  None    None  None
9             trip_miles      DOUBLE  YES  None    None  None
10             trip_time      BIGINT  YES  None    None  None
11   base_passenger_fare      DOUBLE  YES  None    None  None
12                 tolls      DOUBLE  YES  None    None  None
13                   bcf      DOUBLE  YES  None    None  None
14             sales_tax      DOUBLE  YES  None    None  None
15  congestion_surcharge      DOUBLE  YES  None    None  None
16           airport_fee      DOUBLE  YES  None    None  None
17                  tips      DOUBLE  YES  None    None  None
18            driver_pay      DOUBLE  YES  None    None  None
19   shared_request_flag     VARCHAR  YES  None    None  None
20     shared_match_flag     VARCHAR  YES  None    None  None
21    access_a_ride_flag     VARCHAR  YES  None    None  None
22      wav_request_flag     VARCHAR  YES  None    None  None
23        wav_match_flag     VARCHAR  YES  None    None  None

In [41]:
con.execute("DESCRIBE fhv").df()

              column_name column_type null   key default extra
0    dispatching_base_num     VARCHAR  YES  None    None  None
1         pickup_datetime   TIMESTAMP  YES  None    None  None
2        dropOff_datetime   TIMESTAMP  YES  None    None  None
3            PUlocationID      BIGINT  YES  None    None  None
4            DOlocationID      BIGINT  YES  None    None  None
5                 SR_Flag      BIGINT  YES  None    None  None
6  Affiliated_base_number     VARCHAR  YES  None    None  None

In [42]:
con.execute("DESCRIBE green").df()

              column_name column_type null   key default extra
0                VendorID     INTEGER  YES  None    None  None
1    lpep_pickup_datetime   TIMESTAMP  YES  None    None  None
2   lpep_dropoff_datetime   TIMESTAMP  YES  None    None  None
3      store_and_fwd_flag     VARCHAR  YES  None    None  None
4              RatecodeID      BIGINT  YES  None    None  None
5            PULocationID     INTEGER  YES  None    None  None
6            DOLocationID     INTEGER  YES  None    None  None
7         passenger_count      BIGINT  YES  None    None  None
8           trip_distance      DOUBLE  YES  None    None  None
9             fare_amount      DOUBLE  YES  None    None  None
10                  extra      DOUBLE  YES  None    None  None
11                mta_tax      DOUBLE  YES  None    None  None
12             tip_amount      DOUBLE  YES  None    None  None
13           tolls_amount      DOUBLE  YES  None    None  None
14              ehail_fee      DOUBLE  YES  None    None  None
15  improvement_surcharge      DOUBLE  YES  None    None  None
16           total_amount      DOUBLE  YES  None    None  None
17           payment_type      BIGINT  YES  None    None  None
18              trip_type      BIGINT  YES  None    None  None
19   congestion_surcharge      DOUBLE  YES  None    None  None

In [43]:
con.execute("DESCRIBE yellow").df()

              column_name column_type null   key default extra
0                VendorID     INTEGER  YES  None    None  None
1    tpep_pickup_datetime   TIMESTAMP  YES  None    None  None
2   tpep_dropoff_datetime   TIMESTAMP  YES  None    None  None
3         passenger_count      BIGINT  YES  None    None  None
4           trip_distance      DOUBLE  YES  None    None  None
5              RatecodeID      BIGINT  YES  None    None  None
6      store_and_fwd_flag     VARCHAR  YES  None    None  None
7            PULocationID     INTEGER  YES  None    None  None
8            DOLocationID     INTEGER  YES  None    None  None
9            payment_type      BIGINT  YES  None    None  None
10            fare_amount      DOUBLE  YES  None    None  None
11                  extra      DOUBLE  YES  None    None  None
12                mta_tax      DOUBLE  YES  None    None  None
13             tip_amount      DOUBLE  YES  None    None  None
14           tolls_amount      DOUBLE  YES  None    None  None
15  improvement_surcharge      DOUBLE  YES  None    None  None
16           total_amount      DOUBLE  YES  None    None  None
17   congestion_surcharge      DOUBLE  YES  None    None  None
18            Airport_fee      DOUBLE  YES  None    None  None

In [44]:
# Creating a view with selected columns and renamed fields

con.execute("""
            CREATE OR REPLACE VIEW fhvhv_selected AS
            SELECT
              pickup_datetime       AS pickup_datetime,
              request_datetime      AS request_datetime,
              PULocationID          AS pickup_location
            FROM fhvhv
            """)

con.execute("""
            CREATE OR REPLACE VIEW fhv_selected AS
            SELECT
              pickup_datetime       AS pickup_datetime,
              PULocationID          AS pickup_location
            FROM fhv
            """)

con.execute("""
            CREATE OR REPLACE VIEW green_selected AS
            SELECT
              lpep_pickup_datetime  AS pickup_datetime,
              PULocationID          AS pickup_location
            FROM green
            """)

con.execute("""
            CREATE OR REPLACE VIEW yellow_selected AS
            SELECT
              tpep_pickup_datetime  AS pickup_datetime,
              PULocationID          AS pickup_location
            FROM yellow
            """)

In [45]:
# Checking for size of the created view

con.execute("""
            SELECT
            (SELECT COUNT(*) FROM fhvhv) +
            (SELECT COUNT(*) FROM fhv) +
            (SELECT COUNT(*) FROM green) +
            (SELECT COUNT(*) FROM yellow) AS total_rows
            """).df()

   total_rows
0   298930712

In [46]:
# Checking features of the created view

con.execute("DESCRIBE fhvhv_selected").df()

        column_name column_type null   key default extra
0   pickup_datetime   TIMESTAMP  YES  None    None  None
1  request_datetime   TIMESTAMP  YES  None    None  None
2   pickup_location     INTEGER  YES  None    None  None

In [47]:
con.execute("DESCRIBE fhv_selected").df()

       column_name column_type null   key default extra
0  pickup_datetime   TIMESTAMP  YES  None    None  None
1  pickup_location      BIGINT  YES  None    None  None

In [48]:
con.execute("DESCRIBE green_selected").df()

       column_name column_type null   key default extra
0  pickup_datetime   TIMESTAMP  YES  None    None  None
1  pickup_location     INTEGER  YES  None    None  None

In [49]:
con.execute("DESCRIBE yellow_selected").df()

       column_name column_type null   key default extra
0  pickup_datetime   TIMESTAMP  YES  None    None  None
1  pickup_location     INTEGER  YES  None    None  None

In [50]:
# Checking for missing values

con.execute("""
            SELECT COUNT(*) FROM fhvhv_selected WHERE pickup_datetime IS NULL OR pickup_location IS NULL
            UNION ALL
            SELECT COUNT(*) FROM fhv_selected WHERE pickup_datetime IS NULL OR pickup_location IS NULL
            UNION ALL
            SELECT COUNT(*) FROM green_selected WHERE pickup_datetime IS NULL OR pickup_location IS NULL
            UNION ALL
            SELECT COUNT(*) FROM yellow_selected WHERE pickup_datetime IS NULL OR pickup_location IS NULL
            """).df()

   count_star()
0             0
1      14015589
2             0
3             0

In [51]:
con.execute("""
            SELECT COUNT(*) FROM fhv_selected WHERE pickup_datetime IS NULL
            UNION ALL
            SELECT COUNT(*) FROM fhv_selected WHERE pickup_location IS NULL
            """).df()

   count_star()
0             0
1      14015589

In [52]:
con.execute("SELECT COUNT(*) FROM fhv_selected").df()

   count_star()
0      17630326

In [ ]:
# Filtering missing values 

con.execute("""CREATE OR REPLACE VIEW fhv_filtered AS 
            SELECT * FROM fhv_selected WHERE pickup_location IS NOT NULL""")

In [55]:
con.execute("SELECT COUNT(*) FROM fhv_filtered WHERE pickup_datetime IS NULL OR pickup_location IS NULL").df()

   count_star()
0             0

In [ ]:
# Saving the DuckDB databases

def save_view(con, view_name, output_path):
    con.execute(
        f"""
        COPY (
          SELECT *
          FROM {view_name}
        )
        TO '{output_path}'
        (FORMAT PARQUET, COMPRESSION ZSTD);
        """
    )

save_view(con, 'fhvhv_selected', '../01_docs/01_data/02_intermediate/fhvhv_selected.parquet')

save_view(con, 'fhv_filtered', '../01_docs/01_data/02_intermediate/fhv_filtered.parquet')

save_view(con, 'green_selected', '../01_docs/01_data/02_intermediate/green_selected.parquet')

save_view(con, 'yellow_selected', '../01_docs/01_data/02_intermediate/yellow_selected.parquet')