In [ ]:
# Importing necessary libraries

import pandas as pd
import duckdb

In [ ]:
# Creating connect

con = duckdb.connect("../01_docs/01_data/project.duckdb")

In [ ]:
# Testing connection

con.execute("""
SELECT *
FROM read_parquet('../01_docs/01_data/01_raw/yellow_tripdata_2024-07.parquet')
LIMIT 10
""").df()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2024-07-01 00:34:56,2024-07-01 00:46:49,1,3.20,1,N,140,79,1,15.6,3.50,0.5,3.50,0.00,1.0,24.10,2.5,0.00
1,2,2024-06-30 23:48:58,2024-07-01 00:28:04,1,19.48,2,N,132,113,2,70.0,0.00,0.5,0.00,0.00,1.0,75.75,2.5,1.75
2,2,2024-07-01 00:23:18,2024-07-01 00:29:51,1,1.18,1,N,237,145,1,8.6,1.00,0.5,2.72,0.00,1.0,16.32,2.5,0.00
3,1,2024-07-01 00:10:33,2024-07-01 00:27:31,0,9.10,1,N,138,164,1,36.6,10.25,0.5,12.05,0.00,1.0,60.40,2.5,1.75
4,1,2024-07-01 00:07:55,2024-07-01 00:34:34,1,17.70,2,N,132,263,1,70.0,1.75,0.5,10.00,6.94,1.0,90.19,0.0,1.75
5,2,2024-07-01 00:19:42,2024-07-01 00:32:13,1,2.21,1,N,114,170,2,14.9,1.00,0.5,0.00,0.00,1.0,19.90,2.5,0.00
6,1,2024-07-01 00:09:04,2024-07-01 00:14:30,1,0.90,1,N,246,68,1,7.2,3.50,0.5,2.40,0.00,1.0,14.60,2.5,0.00
7,1,2024-07-01 00:34:04,2024-07-01 00:43:13,1,2.10,1,N,68,107,1,12.1,3.50,0.5,2.57,0.00,1.0,19.67,2.5,0.00
8,1,2024-07-01 00:59:52,2024-07-01 01:05:27,2,1.00,1,N,249,79,1,7.9,3.50,0.5,0.09,0.00,1.0,12.99,2.5,0.00
9,1,2024-07-01 00:43:12,2024-07-01 00:50:08,1,0.80,1,N,68,246,1,6.5,3.50,0.5,2.30,0.00,1.0,13.80,2.5,0.00

In [12]:
# Creating a view for each category

def create_view(con, category):
    con.execute(f"""
                CREATE OR REPLACE VIEW {category} AS
                SELECT *
                FROM read_parquet('../01_docs/01_data/01_raw/{category}_tripdata_2024-**.parquet')
                """)

tlc_categories = ['fhv', 'fhvhv', 'green', 'yellow']
for i in tlc_categories:
    create_view(con, i)

In [19]:
con.execute("SELECT * FROM yellow LIMIT 3").df()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1,1.72,1,N,186,79,2,17.7,1.0,0.5,0.00,0.0,1.0,22.70,2.5,0.0
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1,1.80,1,N,140,236,1,10.0,3.5,0.5,3.75,0.0,1.0,18.75,2.5,0.0
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1,4.70,1,N,236,79,1,23.3,3.5,0.5,3.00,0.0,1.0,31.30,2.5,0.0

In [17]:
con.execute("SELECT * FROM green LIMIT 3").df()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2024-01-01 00:46:55,2024-01-01 00:58:25,N,1,236,239,1,1.98,12.8,1.0,0.5,3.61,0.0,NaN,1.0,21.66,1,1,2.75
1,2,2024-01-01 00:31:42,2024-01-01 00:52:34,N,1,65,170,5,6.54,30.3,1.0,0.5,7.11,0.0,NaN,1.0,42.66,1,1,2.75
2,2,2024-01-01 00:30:21,2024-01-01 00:49:23,N,1,74,262,1,3.08,19.8,1.0,0.5,3.00,0.0,NaN,1.0,28.05,1,1,2.75

In [22]:
con.execute("DESCRIBE fhv").df()

              column_name column_type null   key default extra
0    dispatching_base_num     VARCHAR  YES  None    None  None
1         pickup_datetime   TIMESTAMP  YES  None    None  None
2        dropOff_datetime   TIMESTAMP  YES  None    None  None
3            PUlocationID      BIGINT  YES  None    None  None
4            DOlocationID      BIGINT  YES  None    None  None
5                 SR_Flag      BIGINT  YES  None    None  None
6  Affiliated_base_number     VARCHAR  YES  None    None  None

In [21]:
con.execute("DESCRIBE fhvhv").df()

             column_name column_type null   key default extra
0      hvfhs_license_num     VARCHAR  YES  None    None  None
1   dispatching_base_num     VARCHAR  YES  None    None  None
2   originating_base_num     VARCHAR  YES  None    None  None
3       request_datetime   TIMESTAMP  YES  None    None  None
4      on_scene_datetime   TIMESTAMP  YES  None    None  None
5        pickup_datetime   TIMESTAMP  YES  None    None  None
6       dropoff_datetime   TIMESTAMP  YES  None    None  None
7           PULocationID     INTEGER  YES  None    None  None
8           DOLocationID     INTEGER  YES  None    None  None
9             trip_miles      DOUBLE  YES  None    None  None
10             trip_time      BIGINT  YES  None    None  None
11   base_passenger_fare      DOUBLE  YES  None    None  None
12                 tolls      DOUBLE  YES  None    None  None
13                   bcf      DOUBLE  YES  None    None  None
14             sales_tax      DOUBLE  YES  None    None  None
15  congestion_surcharge      DOUBLE  YES  None    None  None
16           airport_fee      DOUBLE  YES  None    None  None
17                  tips      DOUBLE  YES  None    None  None
18            driver_pay      DOUBLE  YES  None    None  None
19   shared_request_flag     VARCHAR  YES  None    None  None
20     shared_match_flag     VARCHAR  YES  None    None  None
21    access_a_ride_flag     VARCHAR  YES  None    None  None
22      wav_request_flag     VARCHAR  YES  None    None  None
23        wav_match_flag     VARCHAR  YES  None    None  None

In [ ]:
# Combining all datasets and saving

con.execute("""
            SELECT
              'fhvhv'               AS service
              hvfhs_license_num     AS hvfhs_license_num
              lpep_pickup_datetime  AS pickup_datetime
              lpep_dropoff_datetime AS dropoff_datetime
              passenger_count       AS passenger_count
              trip_distance         AS trip_distance
              RatecodeID            AS ratecode_id
              store_and_fwd_flag    AS store_and_fwd_flag
              PULocationID          AS pickup_location
              DOLocationID          AS dropoff_location
              trip_type             AS trip_type
              payment_type          AS payment_type
              fare_amount           AS fare_amount
              extra                 AS extra
              mta_tax               AS mta_tax
              tip_amount            AS tip_amount
              tolls_amount          AS tolls_amount
              ehail_fee             AS ehail_fee
              improvement_surcharge AS improvement_surcharge
              congestion_charge     AS congestion_charge
              Airport_fee           AS airport_fee 
              total_amount          AS total_amount
            FROM green

            UNION ALL

            SELECT
              'green'               AS service
              VendorID              AS vendor_id
              lpep_pickup_datetime  AS pickup_datetime
              lpep_dropoff_datetime AS dropoff_datetime
              passenger_count       AS passenger_count
              trip_distance         AS trip_distance
              RatecodeID            AS ratecode_id
              store_and_fwd_flag    AS store_and_fwd_flag
              PULocationID          AS pickup_location
              DOLocationID          AS dropoff_location
              trip_type             AS trip_type
              payment_type          AS payment_type
              fare_amount           AS fare_amount
              extra                 AS extra
              mta_tax               AS mta_tax
              tip_amount            AS tip_amount
              tolls_amount          AS tolls_amount
              ehail_fee             AS ehail_fee
              improvement_surcharge AS improvement_surcharge
              congestion_charge     AS congestion_charge
              Airport_fee           AS airport_fee 
              total_amount          AS total_amount
            FROM green

            UNION ALL

            SELECT 
              'yellow'              AS service
              VendorID              AS vendor_id
              tpep_pickup_datetime  AS pickup_datetime
              tpep_dropoff_datetime AS dropoff_datetime
              passenger_count       AS passenger_count
              trip_distance         AS trip_distance
              RatecodeID            AS ratecode_id
              store_and_fwd_flag    AS store_and_fwd_flag
              PULocationID          AS pickup_location
              DOLocationID          AS dropoff_location
              payment_type          AS payment_type
              fare_amount           AS fare_amount
              extra                 AS extra
              mta_tax               AS mta_tax
              tip_amount            AS tip_amount
              tolls_amount          AS tolls_amount
              improvement_surcharge AS improvement_surcharge
              congestion_charge     AS congestion_charge
              Airport_fee           AS airport_fee 
              total_amount          AS total_amount
            FROM yellow
            """)

ParserException: Parser Error: syntax error at or near "VendorID"

LINE 4:               VendorID AS vendor_id
                      ^