In [1]:
# Importing necessary libraries

import pandas as pd
import duckdb 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Connecting to the DuckDB database

con = duckdb.connect("../01_docs/01_data/project.duckdb")

In [ ]:
# Testing connection

con.execute("""
            SELECT *
            FROM read_parquet('../01_docs/01_data/02_intermediate/fhvhv_selected.parquet')
            LIMIT 10
            """).df()

      pickup_datetime    request_datetime  pickup_location
0 2024-01-01 00:28:08 2024-01-01 00:21:47              161
1 2024-01-01 00:12:53 2024-01-01 00:10:56              137
2 2024-01-01 00:23:05 2024-01-01 00:20:04               79
3 2024-01-01 00:41:04 2024-01-01 00:35:46              234
4 2024-01-01 00:57:21 2024-01-01 00:48:19              148
5 2024-01-01 00:06:15 2024-01-01 00:03:47              255
6 2024-01-01 00:29:47 2024-01-01 00:22:51               95
7 2024-01-01 00:57:50 2024-01-01 00:45:34              213
8 2024-01-01 00:16:00 2024-01-01 00:11:51              209
9 2024-01-01 00:33:15 2024-01-01 00:26:48              113

In [9]:
# Creating views for easier querying

def create_view_int(con, category, suffix="selected"):
    con.execute(f"""
                CREATE OR REPLACE VIEW {category} AS
                SELECT *
                FROM read_parquet('../01_docs/01_data/02_intermediate/{category}_{suffix}.parquet')
                """)

create_view_int(con, "fhvhv")

create_view_int(con, "fhv", "filtered")

create_view_int(con, "green")

create_view_int(con, "yellow")

In [ ]:
# Selecting how much a ride should appear in the map

con.execute("""
            SELECT AVG(pickup_datetime - request_datetime) AS avg_wait_time
            FROM fhvhv
            """).df()

           avg_wait_time
0 0 days 00:04:50.304964